### ISSUE TITLE
emacs in startup, error: init-better-editing.el has error in emacs 26.0.50

### ISSUE THREAD

**Issue by bsed** [samrayleung/emacs.d#1]
Warning: looking-back called with 1 argument, but requires 2-3

you should update  `(unless (looking-back "\\b" )` 

to 
```
 (unless (looking-back "\\b" (beginning-of-line))
```

**Comment by bsed** [comment]
sanityinc-tomorrow-eighties-theme 需要手动安装

```
M-x package-install RET color-theme-sanityinc-tomorrow RET

```

**Comment by samrayleung** [comment]
I am so sorry, because this is my personal, I never imagine that someone will use my configuration, so there is some unfixed issues here I know before. I will fix it right now.

**Comment by samrayleung** [comment]
I have fixed warning and issue that themes need to be installed manually. Thanks for your feedback

**Comment by bsed** [comment]
thank you. ^.^

**Comment by bsed** [comment]
i git pull new version,but tips on `Error (use-package): org :config: Cannot open load file: Not a directory, ob-shell`

**Comment by samrayleung** [comment]
Because the version of Emacs I am using is 25.2, I have not tested in Emacs 26.0. After you change `shell . t` to `sh . t`, could you fix this `could not open file `error ?

**Comment by bsed** [comment]
I have fix this error~
