### ISSUE TITLE
Error (use-package): general/:config: Wrong type argument: keymapp, nil

### ISSUE THREAD

**Issue by bsed** [samrayleung/emacs.d#10]
![screenshot_2018-01-06_17-04-25](https://user-images.githubusercontent.com/10845087/34638298-b06215c0-f303-11e7-9611-310fb088889e.png)

**Comment by bsed** [comment]
我这个不知道如何解决了

**Comment by samrayleung** [comment]
在 `init-keybinding` 文件找到关于Eshell 的keybinding:
```
		  ;; Eshll-mode
		  (general-imap :keymaps 'eshell-mode-map
				"C-u" 'eshell-kill-input
				[remap evil-paste-from-register] 'samray/esh-history
				"C-r" 'samray/esh-history
				)
		  (general-define-key :keymaps 'eshell-mode-map
				      "C-c C-a" 'samray/eshell-sudo-toggle
				      [remap eshell-bol] 'samray/eshell-sudo-toggle
				      "C-a" 'samray/eshell-maybe-bol
				      "C-l" 'samray/eshell-clear-buffer
				      "C-k" 'eshell-kill-process
				      [remap samray/smarter-move-beginning-of-line] 'samray/eshell-maybe-bol
				      [remap evil-insert-digraph] 'eshell-kill-process
				      ))
```
然后注释掉，应该可以解决这个问题．

**Comment by samrayleung** [comment]
这个问题有点奇怪，因为这个问题我原来也遇到过，但是只是在 windows 或者是 terminal 下面才会出现，所以我就加了一行判断:
```emacs-lisp
	    (if (and (not (samray/is-windows))
		     window-system)
		(progn
;;do something
         )
      )

```

**Comment by bsed** [comment]
我这个不知道如何解决了

**Comment by bsed** [comment]
![image](https://user-images.githubusercontent.com/10845087/34639562-e7b47fcc-f31c-11e7-9d70-f7a13a2fff05.png)
谢谢,解决了.
![image](https://user-images.githubusercontent.com/10845087/34639569-02a9e146-f31d-11e7-9a47-43ab66f9ef46.png)

**Comment by samrayleung** [comment]
这个问题我找到了原因，这个是 `eshell` 的一个 bug.参考:
https://lists.gnu.org/archive/html/bug-gnu-emacs/2016-02/msg01532.html
https://github.com/noctuid/general.el/issues/80
