### ISSUE TITLE
how set chinese-pyim shortcut key

### ISSUE THREAD

**Issue by bsed** [samrayleung/emacs.d#2]
how to remove mouse middle key scroll

**Comment by samrayleung** [comment]
If you want to disable mouse scrolling, there are two options:
you could add
```
;;; Disable mouse scrolling
(mouse-wheel-mode -1)
```
in your config file or you could just
`M-x customize-option mouse-wheel-mode` 
and set it to nil and save. Hope this could help you out :)

**Comment by bsed** [comment]
thank  you
