### ISSUE TITLE
when i click SPC a s ,use `ag`  tips on error

### ISSUE THREAD

**Issue by bsed** [samrayleung/emacs.d#5]
![selection_071](https://cloud.githubusercontent.com/assets/10845087/26635800/7cafdb58-464d-11e7-96fd-377eede663b7.png)

**Comment by bsed** [comment]
why bind: Key with naem "right" does not have any mapping

**Comment by samrayleung** [comment]
It's weird , I have never occur this error, could you tell me how reproduce this error.Before I fix this error, you could install ripgrep, and use counsel-rg by press SPC s r, it is similiar to counsel-ag, but faster and better, in my opinion

**Comment by bsed** [comment]
run eamcs, and press `SPC a s`, search `setq` , occur this error,

**Comment by bsed** [comment]
run eamcs, and press SPC s r, search setq , occur this error, ^.^

**Comment by samrayleung** [comment]
I have tried Emacs 25.2,  it seems everything is ok, I will try my .emacs.d on Emacs 26, but it will take some time, hope you could be patient :)

**Comment by samrayleung** [comment]
Could you give me more information about your platform and Emacs? You platform is Windows , Linux or Mac; You install emacs from package manager or build from source ?

**Comment by bsed** [comment]
Hello, sir, my system is `Ubuntu 17.10`, EMAS version is `Emacs 26.0.50`， shell version  is fish, I find it is used together with Emacs and fish trigger, when I switch to bash or Zsh, no problems, thank you
