### ISSUE TITLE
happen triple-mouse-4 error？

### ISSUE THREAD

**Issue by bsed** [samrayleung/emacs.d#6]
![selection_073](https://cloud.githubusercontent.com/assets/10845087/26724727/82992908-47cd-11e7-8214-3aca276c57c5.png)

**Comment by samrayleung** [comment]
Hey, buddy, to be honest, I have to take some final  exams these day, so I hope I could not fix issues immediately, I have to do a apologize :)

**Comment by samrayleung** [comment]
Hey,buddy , I have to take some final exams these day, so I am afraid i could fix isueses immediately. My apology :(

**Comment by samrayleung** [comment]
Could you tell me how to reproduce this Error?

**Comment by bsed** [comment]
This problem occurs when I execute commands `emacs ~/.emacs.d/init.el` under shell, open files, and then scroll the mouse.

**Comment by samrayleung** [comment]
I can not reproduce this issue, but from the screenshot you posted, it seems you have pressed the `left-margin` key. Thus, If you press `Ctrl` key  and then scroll the middle key, Emacs will show this issue.

**Comment by bsed** [comment]
i don't press ctrl key ..

**Comment by samrayleung** [comment]
Is there something like this:
![emacs_issue](https://cloud.githubusercontent.com/assets/14180681/26769232/d29ff102-49df-11e7-8df4-8f671ba31260.png)
But this issue only happen when I scroll mouse with `Ctrl` pressed. It is so weird :(

**Comment by samrayleung** [comment]
And this only happen when I run Emacs in a terminal instead of GUI Emacs .

**Comment by samrayleung** [comment]
It seems you have pressed other key:
![82992908 47cd 11e7 8214 3aca276c57c5](https://cloud.githubusercontent.com/assets/14180681/26770034/1d50577c-49e6-11e7-8e04-76f4275ebd26.png)

**Comment by bsed** [comment]
I run Emacs in a terminal instead of GUI Emacs, yet.I didn't press Ctrl,how do I block the CTRL key?

**Comment by samrayleung** [comment]
Actuall, I could not press the right key to produce the error that `<left-margin> <triple-mouse-4> is undefined`. How could you press `<triple-mouse-4>` in your Emacs? According to the  [Emacs manual](https://www.gnu.org/software/emacs/manual/html_node/emacs/Mouse-Buttons.html):
>The symbols for mouse events also indicate the status of the modifier keys, with the usual prefixes ‘C-’, ‘M-’, ‘H-’, ‘s-’, ‘A-’ and ‘S-’. These always precede ‘double-’ or ‘triple-’, which always precede ‘drag-’ or ‘down-’. 

So It turns out that you are pressing `Ctrl` key when you scroll mouse, but you are so sure you haven't, so it is so weird. Maybe you could press `C-h k` and then scroll mouse to see what is going on?

**Comment by samrayleung** [comment]
And I found something simliar in Emacs bug list [\<left-margin\> \<double-wheel-down\> is undefined](https://lists.gnu.org/archive/html/bug-gnu-emacs/2010-02/msg00184.html), you could check this

**Comment by bsed** [comment]
how to check  `<left-margin> <double-wheel-down>` ?  I've blocked these keys, but they will still show up

**Comment by samrayleung** [comment]
And I found something simliar in Emacs bug list [\<left-margin\> \<double-wheel-down\> is undefined](https://lists.gnu.org/archive/html/bug-gnu-emacs/2010-02/msg00184.html), you could check this

**Comment by samrayleung** [comment]
You could run vanilla Emacs by `emacs -Q`, and scroll your mouse again. If this issue occurs again, It is something wrong with the configuration file, or It is something wrong with Emacs :)

**Comment by bsed** [comment]
the problem didn't happen

**Comment by samrayleung** [comment]
Well, It is something about with configuration file, I will try to figure out what is wrong, be patient, buddy :)

**Comment by bsed** [comment]
The configuration file error is not easy to find， buddy .

**Comment by samrayleung** [comment]
I could not correctly reproduce this error, this issue only happen When I run Emacs 26.0.50 in Ubuntu 17 (in virtualbox), and no matter how I scroll mouse, everything is fine. But when I scroll mouse with `Ctrl` key pressed, everything mess up.

**Comment by bsed** [comment]
Aha, sadly, then I'll close the question， thank you .

**Comment by samrayleung** [comment]
I am sorry for that, my apology :(

**Comment by bsed** [comment]
I know how to solve the problem， need to modify [custom.el](https://github.com/samrayleung/emacs.d/blob/master/lisp/custom.el) add an instruction

**Comment by samrayleung** [comment]
So could you fix this issue ?

**Comment by bsed** [comment]
i paste `(mouse-wheel-mode 1)` in custom.el  end
