### ISSUE TITLE
emacs init 

### ISSUE THREAD

**Issue by bsed** [samrayleung/emacs.d#7]
```
Warning (bytecomp): cl package required at runtime [5 times]
Warning (bytecomp): ‘syntax-begin-function’ is an obsolete variable (as of 25.1). [2 times]
Warning (bytecomp): cl package required at runtime
Warning (bytecomp): the following functions are not known to be defined: mmm-name-at,
    mmm-names-alist, mmm-syntax-region
Warning (bytecomp): cl package required at runtime
Warning (bytecomp): ‘syntax-begin-function’ is an obsolete variable (as of 25.1).
Warning (bytecomp): ‘font-lock-fontify-buffer’ is for interactive use only; use ‘font-lock-ensure’ or ‘font-lock-flush’ instead.
Warning (bytecomp): ‘font-lock-syntactic-keywords’ is an obsolete variable (as of 24.1); use ‘syntax-propertize-function’ instead.
Warning (bytecomp): cl package required at runtime [3 times]
```

**Comment by bsed** [comment]
GNU Emacs 25.1.1
Copyright (C) 2016 Free Software Foundation, Inc.
GNU Emacs comes with ABSOLUTELY NO WARRANTY.
You may redistribute copies of GNU Emacs
under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING.

**Comment by samrayleung** [comment]
This issue will occur when Emacs install and compile package from melpa, becuase some functions in  packages are obsolete.

**Comment by bsed** [comment]
I  don't  this kind of mistake why?

**Comment by samrayleung** [comment]
不太懂你的意思 :)

**Comment by bsed** [comment]
意思是我是不是可以忽略这种错我。。。 英语有点儿渣

**Comment by samrayleung** [comment]
其实这些只是因为某些 Emacs api 改动了而使用了该　api的包没有及时更新而出现　warning, 一般是不会造成大的印象的．但是如果你是完美主义者，受不了这些　warning 的话，你可以去给对应的包的作者提　issue, 催催他们更新对应的 api :)

**Comment by bsed** [comment]
谢谢， 说中文就方便多啦。那我 去提issure
