### ISSUE TITLE
Rust intelligent aren't too smart

### ISSUE THREAD

**Issue by bsed** [samrayleung/emacs.d#8]

**Comment by samrayleung** [comment]
现在可以各编辑器用的只有[racer](https://github.com/racer-rust/racer#installation) 作为补全的后端．Rust 社区也提到了希望有更加强大的 IDE 特性支持，而Rust-lang 团队也在开发基于　LSP 的[RLS](https://github.com/rust-lang-nursery/rls). 你也可以去尝试折腾一样．我试过，还是很不稳定．所以，我也很无奈　:(

**Comment by samrayleung** [comment]
迟点我会再去试试水　[lsp-mode](https://github.com/emacs-lsp/lsp-mode) [rls](https://github.com/rust-lang-nursery/rls)

**Comment by bsed** [comment]
racer 作为补全的后端 说的应该是这类的[Repository for the Rust Language Server (aka RLS)](https://github.com/rust-lang-nursery/rls), 我现在 再vs code 下用 rls 还行，

**Comment by samrayleung** [comment]
也不能说是借鉴微软．因为本来　language server protocol 就是微软和red hat 牵头搞的一套东西．racer 做补全的后端，指的是类似 python 的jedi ,而不是rls. 我只是使用 Emacs, 所以也不知道　vs code 怎么样．但是作为微软的开源项目，感觉肯定会对微软牵头的项目大力支持的．

**Comment by bsed** [comment]
坐等大神把 emacs rust 配合好， 这个 issue 我先不关闭了。

**Comment by samrayleung** [comment]
我新增了一个文件来放置lsp 的配置　[init-lsp.el](https://github.com/samrayleung/emacs.d/blob/master/lisp/init-lsp.el)．现在emacs-lsp 支持的语言就是几种，而我只是添加了　python 和 rust 两种语言．安装跟其他的 package 一样，都是使用 use-package 来安装．只是安装对应的 server 略麻烦．python 需要 clone python-lsp repo 然后使用 pip 安装到本地．而 rust 可以使用 rustup 直接安装．按照文档来操作就可以了．不得不说 rls 的补全真的强了一个量级的，用的非常顺手，但是　 :( 有各种小问题，比如说突然说找不到 server, 或者是无法关闭　Emacs , 只能 kill emacs. 虽说还有很多问题，但是我觉得还是值得尝试．

**Comment by samrayleung** [comment]
更新：我还是删除了 lsp-mode,　感觉还是用太多的问题，太不稳定了．

**Comment by bsed** [comment]
好的，我已经clone 了，现在我用的 vs code rls 玩 rust 挺方便的，谢谢。
